// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "Utils/MathUtils.cginc"

RWTexture3D<uint> Result;

float iTime;


[numthreads(8,8,8)]

void CSMain (uint3 id : SV_DispatchThreadID)
{
    //La lluvia
    uint x = id.x + iTime * 56.21;
    uint y = id.y + iTime * 72.21;
    uint z = id.z;

    uint state = WangHash(x * 612 + y * 125 + z * 65);
    float value = NextFloat(0, 1, state);

    Result[id] = value > 0.99 ? 3 : 0;
}
