// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWTexture3D<uint> Result;

float iTime;


[numthreads(8,8,8)]

void CSMain (uint3 id : SV_DispatchThreadID)
{
    float sphereDist = 5;
    float3 spherePos = float3(20, 25, 20) + float3(5 * sin(iTime * 1), 0, 5 * cos(iTime * 1));
    if(distance(spherePos, id) < sphereDist)
    {
        Result[id] = 1;
        return;
    }


     Result[id] = 0;
}
